

# Python Advanced - Data Science Foundation

**SET THE WORKING DIRECTORY SO THAT WE DO NOT HAVE TO THINK ABOUT PATH PROBLEMS**

Please ensure all your folder names <font color='red'><b>do not have a space & use forward slash (/)</b></font>

In [5]:
# Please ensure the path follows the rules we had discussed and ensure a '/' at the last
your_local_path="C:/Users/tejks/Desktop/ML/practice/"

In [6]:
def func_python(N):
    d=0
    for i in range(N):
        d += (i % 3 - 1) * i
    return d

In [7]:
%timeit func_python(10000)

2.84 ms ± 103 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
distance = [45,50,35]
speed = [5,10,7]


time = distance/speed 
print (time)

TypeError: unsupported operand type(s) for /: 'list' and 'list'

**Introduction to NumPy**

NumPy (short form for Numerical Python) is the most fundamental package designed for scientific computing and data analysis. Most of the other packages such as pandas, statsmodels are built on top of it, and is an important package to know and learn about. At the heart of NumPy is a data structure called **ndarray**. ndarray is a basically a multi-dimensional array that is built specifically for the purpose of numerical data analysis. Python also has array capabilities, but they are more generic. <b>The advantage of using ndarray is that processing is extremely efficient and fast.</b> 

You can perform standard mathematical operations on either individual elements or complete array. The range of functions covered is <b>linear algebra, statistical operations, and other specialized mathematical operations</b>. For our purpose, we need to know about <b>ndarray and the range of mathematical functions that are relevant to our research purpose</b>. If you already know languages such as C, Fortran, then you can integrate NumPy code with code written in these languages and can pass NumPy arrays seamlessly. 

From an overall perspective, understanding of <b>NumPy will help us in using pandas effectively as it is built on top of NumPy and frequently we will also be using functions of NumPy in research work</b>. In the current session, we will only look at some of the most important features of NumPy. For a full listing of NumPy features, please visit http://wiki.scipy.org/Numpy_Example_List .

Possible application of NumPy package in research work are:
<i>
+ Algorithmic operations such as sorting, grouping and set operations
+ Performing repetitive operations on whole arrays of data without using loops
+ Data merging and alignment operations
+ Data indexing, filtering, and transformation on individual elements or whole arrays
+ Data summarization and descriptive statistics
</i>
**Installing NumPy**

In order to check if NumPy is installed, go to Package Manager and type NumPy. You will get a list of packages with names closely matching to NumPy. For our purpose, we need to focus on package named numpy 1.xx. If the package is not installed, click on Install. 

**Importing NumPy**

In order to be able to use NumPy, first import it using import statement

In [15]:
import numpy as np


The above statement will import all of NumPy into your workspace. For starters its good, but if you are doing performance intensive work, then saving space is of importance. In such cases, you can import specific modules of NumPy by using

In [16]:
from numpy import array
from numpy import arange

In [17]:
# How we have overcome the prior challenge using 
dist = array(distance) #numpy takes whole array as integers and applies the operation in them
spd = np.array(speed)
print (dist)
print (spd)
time= dist/spd
print (time)
len(time)

[45 50 35]
[ 5 10  7]
[ 9.  5.  5.]


3

ndarray
The most important data structure in NumPy is an n-dimensional array object. Using ndarray, you can store large multidimensional datasets in Python. Being an array, you can <b>perform mathematical operations on these arrays either one element at a time or on complete arrays without using loops</b>. The way to initialize an array object is

In [18]:
a=[1,2,3,4,5]                                 # initialize a list and assign values to it
b=[10,20,30,40]
print (a + b)                              #concatenation happens if we simply add 2 arrays
#print (a + 5)                               #Want to add '5' to all the elements in the list
#c = [val + 5 for val in a]           
#print (c)

[1, 2, 3, 4, 5, 10, 20, 30, 40]


In [19]:
f = np.array((1,2,3,4,5))                       # initializes an array a and assigns values to it
g = np.array((10,20,30,40,50))                  # initializes another array g
print (f)                                   #dimensions of the array should be same
print (g)                                
print(f+g) 
print (f+5)                  
f**2
g**3

[1 2 3 4 5]
[10 20 30 40 50]
[11 22 33 44 55]
[ 6  7  8  9 10]


array([  1000,   8000,  27000,  64000, 125000], dtype=int32)

In [20]:
f = np.array((1,2,3,4,"pal"))                       # initializes an array a and assigns values to it
g = np.array((10,20,30,40,50))                  # initializes another array g
print (f)                                   #dimensions of the array should be same
type(f) #everything is converted to string
#print (g)                                
                         #datatype - object >float>integer
#print(f+g) 
#print (f+5)                  
#f**2
#g**3

['1' '2' '3' '4' 'pal']


numpy.ndarray

In [21]:
f = np.array((1,2,3,4,"pal"))                       # initializes an array a and assigns values to it
g = np.array((10,20,30,40,50))                  # initializes another array g
print (f)                                   #dimensions of the array should be same
f.dtype #everything is converted to string
#print (g)                                
                         #datatype - object >float>integer
#print(f+g) 
#print (f+5)                  
#f**2
#g**3

['1' '2' '3' '4' 'pal']


dtype('<U11')

In [24]:
c = array(arange(10))                           #arange function here works as a sequence or counter in increments of 1
print ('array:                ', c)
print()
print()

anarray = array(np.arange(5,56,5))                 #arange function here works as a sequence or counter in increments of 5
print ('anarray:              ', anarray)
print()
print()

onemorearray = array(np.linspace(30,100,5))           #linspace function here creates 11 evenly spaced numbers over a specified interval
print ('onemorearray:         ', onemorearray)
#print ('Rounded onemorearray: ', np.round(onemorearray,0))
onemorearray.sum()

array:                 [0 1 2 3 4 5 6 7 8 9]


anarray:               [ 5 10 15 20 25 30 35 40 45 50 55]


onemorearray:          [  30.    47.5   65.    82.5  100. ]


325.0

With each ndarray are associated two attributes: shape of the array, and type of the array. The <font color='red'><b>shape</b> of the array tells you about <b><u>dimensionality</u></b> of the array (rows and columns), and <b>type</b> of the array tells you about the <b><u>data type</u></b> contained</font> in the array.

In [32]:
data = np.array((32,45,123,756,23,2123,1,2,3,4,5,6,6,5,4,3,2,1,78,89,87,76,54,31))
#data = data.reshape(8,3)
data2 = data.reshape(2,2,2,3)
print(data)
print ("*****")
print (data2)
print(data2.shape)
print(data2.dtype)
print(data2.size)
even_data = (data % 2 = 0)
print (even_data)
data[even_data]

SyntaxError: invalid syntax (<ipython-input-32-5e8909540d77>, line 10)

In [26]:
np.zeros(50)                         # Make a 50, 0 numbered single dimensional array

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [27]:
np.zeros((3,5)) + 6                     # Make a 15, 0 numbered 2 dimensional array

array([[ 6.,  6.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  6.,  6.]])

In [28]:
np.ones(30) + 7                         # Make a 30, 1 numbered single dimensional array

array([ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,
        8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,
        8.,  8.,  8.,  8.])

In [29]:
np.ones((5,9))                       # Make a 45, 1 numbered 2 dimensional array

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [30]:
np.eye(5)                            # creates a 5*5 identity matrix. 

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [31]:
np.diag(array([1,3,5,3,4,5]))        # Populate the disgonal elements only

array([[1, 0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])

**pandas**

Pandas is the primary package for performing data analysis tasks in Python. pandas derives its name from <b>PANel Data AnalysiS</b> and is the fundamental package that provides <b>relational data structures (think Excel, SQL type) and a host of capabilities to play with those data structures</b>. It is the most widely used package in Python for data analysis tasks, and is very good to work with <b>cross sectional, time series, and panel data analysis</b>. Python sits on top of NumPy and can be used with NumPy arrays and the functions in NumPy. How is pandas suited for a researcher’s needs:
<i>
+ Has a tabular data structure that can hold both <b>homogenous and heterogenous data</b>.
+ Very <b>good indexing capabilities</b> that makes data alignment and merging easy.
+ Good <b>time series functionality</b>. No need to use different data structures for time series and cross sectional data. Allows for both <b>ordered and unordered time-series data</b>.
+ A host of <b>statistical functions</b> developed around NumPy and pandas that makes a researcher’s task easy and fast.
+ Programming is lot <b>simpler and faster</b>.
+ Easily handles <b>data manipulation and cleaning</b>.
+ Easy to expand and shorten data sets. <b>Comprehensive merging, joins, and group by functionality to join multiple data sets</b>.
</i>

**Installing pandas** 

In order to check if pandas is installed, go to Package Manager and type pandas. By default, pandas already comes installed with a distribution of Canopy. If the package is not installed, click on Install.

**Importing pandas**

In order to be able to use NumPy, first import it using import statement


In [33]:
import pandas as pd                         # This will import pandas into your workspace

In [34]:
import numpy as np                          # We will be using numpy functions so import numpy

**Data Structures in pandas**

There are two basic data structures in pandas: <b><i>Series and DataFrame</i></b>

**Series:** It is similar to a NumPy 1-dimensional array. In addition to the values that are specified by the programmer, <b>pandas attaches a label to each of the values</b>. If the labels are not provided by the programmer, then pandas assigns labels ( 0 for first element, 1 for second element and so on). A benefit of assigning labels to data values is that it becomes easier to perform manipulations on the dataset as the whole dataset becomes more of a dictionary where each value is associated with a label. 


In [35]:
series1 = pd.Series([10,20,30,40])
series1

0    10
1    20
2    30
3    40
dtype: int64

In [36]:
series1.values

array([10, 20, 30, 40], dtype=int64)

In [37]:
series1.index

RangeIndex(start=0, stop=4, step=1)

If you want to specify custom index values rather than the default ones provided, you can do so using the following command

In [38]:
series2 = pd.Series([10,20,30,40,50], index=[1,2,3,4,5])
series2

1    10
2    20
3    30
4    40
5    50
dtype: int64

The ways of accesing elements in a Series object are similar to what we have seen in NumPy, and you can perform NumPy operations on Series data arrays.

In [39]:
series2[6]                  # How to print 30 from the series

KeyError: 6

In [40]:
series2['three']            # Another way to print 30 from the series

KeyError: 'three'

In [41]:
series2[['one', 'three', 'five']]

KeyError: "None of [['one', 'three', 'five']] are in the [index]"

In [42]:
series2[[0,1,3]]

0     NaN
1    10.0
3    30.0
dtype: float64

In [43]:
series2 + 4            # Add 4 to every element

1    14
2    24
3    34
4    44
5    54
dtype: int64

In [44]:
series2 ** 3           # Cube every element 

1      1000
2      8000
3     27000
4     64000
5    125000
dtype: int64

In [45]:
series2[series2>30]    # Find all values greater than 30

4    40
5    50
dtype: int64

In [46]:
np.sqrt(series2)       # Get the square roots of all the values

1    3.162278
2    4.472136
3    5.477226
4    6.324555
5    7.071068
dtype: float64

If you have a dictionary, you can <b>create a Series data structure from that dictionary</b>. Suppose you are interested in EPS values for firms and the <i>values come from different sources and is not clean. In that case you dont have to worry about cleaning and aligning those values</i>. 

In [47]:
years = [91, 90, 92, 93, 94, 95, 96, 97]
f1 = {90:8, 91:9, 92:7, 93:8, 94:9, 95:11, 96:13}
firm1 = pd.Series(f1,index=years)                     # Extra element in VALUE not an issue
firm1

91     9.0
90     8.0
92     7.0
93     8.0
94     9.0
95    11.0
96    13.0
97     NaN
dtype: float64

In [48]:
f2 = {90:14,92:9, 93:13, 94:5}                      
firm2 = pd.Series(f2,index=years)                   # Extra element in the KEY is handled as NaN
firm2

91     NaN
90    14.0
92     9.0
93    13.0
94     5.0
95     NaN
96     NaN
97     NaN
dtype: float64

NaN stands for missing or NA values in pandas. Make use of isnull() function to find out if there are any missing values in the data structure.

In [49]:
pd.isnull(firm2)

91     True
90    False
92    False
93    False
94    False
95     True
96     True
97     True
dtype: bool

A key feature of Series data is structures is that you don't have to worry about data alignment. For example, if we have run a word count program on two different files and we have the following data structures

In [50]:
dict1 = {'finance': 10, 'earning': 5, 'debt':8}
dict2 = {'finance' : 8, 'compensation':4, 'earning': 9}
count1 = pd.Series(dict1)
count2 = pd.Series(dict2)
print (count1)
print (count2)

debt        8
earning     5
finance    10
dtype: int64
compensation    4
earning         9
finance         8
dtype: int64


If we want to calculate the sum of common words in combined files, then we dont have to worry about data alignment. If we want to include all words, then we can take care of NaN values and compute the sum. By default, Series data structure ignores NaN values. NaN values stand for missing data values.

In [51]:
count1+count2                                # Sum values on key based retrieval. Non matching keys become NaN

compensation     NaN
debt             NaN
earning         14.0
finance         18.0
dtype: float64

**Data Frame**

DataFrame is a <b>tabular data structure</b> in which data is laid out in <b>rows and column</b> format (similar to a CSV and SQL file), but it can also be <b>used for higher dimensional data</b> sets. The DataFrame object can contain homogenous and heterogenous values, and can be thought of as a logical extension of Series data structures. In contrast to <u>Series</u>, where there is <b>one index</b>, a <u>DataFrame</u> object has <b>one index for column and one index for rows</b>. This allows flexibility in accessing and manipulating data.

In [52]:
data = pd.DataFrame({'price':[95, 25, 85, 41, 78],
                     'ticker':['AXP', 'CSCO', 'DIS', 'MSFT', 'WMT'],
                     'company':['American Express', 'Cisco', 'Walt Disney','Microsoft', 'Walmart']})
data

company  price ticker
0  American Express     95    AXP
1             Cisco     25   CSCO
2       Walt Disney     85    DIS
3         Microsoft     41   MSFT
4           Walmart     78    WMT

If a column is passed with no values, it will simply have NaN values

In order to access a column, simply mention the column name

In [53]:
data['company']                          # Print only company names

0    American Express
1               Cisco
2         Walt Disney
3           Microsoft
4             Walmart
Name: company, dtype: object

In [54]:
data.company                            # Another way to print only company names

0    American Express
1               Cisco
2         Walt Disney
3           Microsoft
4             Walmart
Name: company, dtype: object

In [55]:
print (data.ix[2])                              # Print the row corresponding to the given Index

company    Walt Disney
price               85
ticker             DIS
Name: 2, dtype: object


C:\Users\OM\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


In [56]:
data.ix[data.ticker=='DIS']            # Print the row corresponding to the ticker that is 'DIS'

company  price ticker
2  Walt Disney     85    DIS

In order to add additional columns

In [57]:
data['Year'] = 2014                       # Add additional column Year. Populate value of 2014 in all the rows.
data

company  price ticker  Year
0  American Express     95    AXP  2014
1             Cisco     25   CSCO  2014
2       Walt Disney     85    DIS  2014
3         Microsoft     41   MSFT  2014
4           Walmart     78    WMT  2014

In [58]:
data['pricesquared'] = data.price**2      # Square all the prices and add another column 'pricesquared'.
data

company  price ticker  Year  pricesquared
0  American Express     95    AXP  2014          9025
1             Cisco     25   CSCO  2014           625
2       Walt Disney     85    DIS  2014          7225
3         Microsoft     41   MSFT  2014          1681
4           Walmart     78    WMT  2014          6084

In [59]:
del data['pricesquared']                  # Delete column 'pricesquared'
data

company  price ticker  Year
0  American Express     95    AXP  2014
1             Cisco     25   CSCO  2014
2       Walt Disney     85    DIS  2014
3         Microsoft     41   MSFT  2014
4           Walmart     78    WMT  2014

In [60]:
data['pricesquared'] = np.NaN             # Create column 'pricesquared' with NaN values
data

company  price ticker  Year  pricesquared
0  American Express     95    AXP  2014           NaN
1             Cisco     25   CSCO  2014           NaN
2       Walt Disney     85    DIS  2014           NaN
3         Microsoft     41   MSFT  2014           NaN
4           Walmart     78    WMT  2014           NaN

In [61]:
data['sequence'] = np.arange(2014,2024,2)         # Add column 'sequence' and populate sequence of numbers from 1 to 5
data

company  price ticker  Year  pricesquared  sequence
0  American Express     95    AXP  2014           NaN      2014
1             Cisco     25   CSCO  2014           NaN      2016
2       Walt Disney     85    DIS  2014           NaN      2018
3         Microsoft     41   MSFT  2014           NaN      2020
4           Walmart     78    WMT  2014           NaN      2022

You can use NumPy functions inside DataFrame objects.

In [62]:
dataframe = pd.DataFrame(np.random.randn(3,3),columns=['one','two','three'])  # Create array of 3*3 dimensionality using standard normally distributed random vales
dataframe

one       two     three
0 -1.063507 -0.475840  0.391509
1  0.665202 -1.617099 -0.688962
2 -0.144344 -1.425436 -1.688832

In [63]:
np.abs(dataframe)                   # Absolute value

one       two     three
0  1.063507  0.475840  0.391509
1  0.665202  1.617099  0.688962
2  0.144344  1.425436  1.688832

In [64]:
f = lambda x:x.max()-x.min()        # We have option to use a powerful lambda function feature. Get the range in a column
abs(dataframe).apply(f)

one      0.919162
two      1.141258
three    1.297323
dtype: float64

In [65]:
abs(dataframe).apply(f,axis=1)           # Apply lambda function on the row and not column as we did in the previous example

0    0.671997
1    0.951897
2    1.544488
dtype: float64

In [66]:
def f(x):
    return pd.Series([np.mean(x), x.max(), x.min()], index=['mean','max','min'])
print(dataframe)
dataframe.apply(f,axis=1)

        one       two     three
0 -1.063507 -0.475840  0.391509
1  0.665202 -1.617099 -0.688962
2 -0.144344 -1.425436 -1.688832


mean       max       min
0 -0.382612  0.391509 -1.063507
1 -0.546953  0.665202 -1.617099
2 -1.086204 -0.144344 -1.688832

In [67]:
print(dataframe)
dataframe.sum()                          # Column wise sum

        one       two     three
0 -1.063507 -0.475840  0.391509
1  0.665202 -1.617099 -0.688962
2 -0.144344 -1.425436 -1.688832


one     -0.542649
two     -3.518375
three   -1.986285
dtype: float64

In [68]:
dataframe.sum(axis=1)                    # Row wise sum

0   -1.147837
1   -1.640859
2   -3.258613
dtype: float64

In [69]:
print(dataframe)
dataframe.cumsum()                 # Get cumulative sum

        one       two     three
0 -1.063507 -0.475840  0.391509
1  0.665202 -1.617099 -0.688962
2 -0.144344 -1.425436 -1.688832


one       two     three
0 -1.063507 -0.475840  0.391509
1 -0.398305 -2.092939 -0.297453
2 -0.542649 -3.518375 -1.986285

In [70]:
dataframe.describe()

one       two     three
count  3.000000  3.000000  3.000000
mean  -0.180883 -1.172792 -0.662095
std    0.864933  0.611138  1.040431
min   -1.063507 -1.617099 -1.688832
25%   -0.603925 -1.521268 -1.188897
50%   -0.144344 -1.425436 -0.688962
75%    0.260429 -0.950638 -0.148726
max    0.665202 -0.475840  0.391509

If you have non-numeric data, then applying describe function would produce statistics such as <b>count, unique, frequency</b>. In addition to this, you can also calculate <b>skewness (skew), kurtosis (kurt), percent changes, difference, and other statistics</b>.

**Missing Data**

Pandas have a number of features to deal with <b>missing data</b>. We have seen an example of the case of descriptive statistics, where missing values are not taken into account while calculating the descriptive statistics. Missing data is denoted by NaN. 

In [71]:
import pandas as pd
years = [90, 91, 92, 93, 94, 95]
f1 = {90:8, 91:9, 92:7, 93:8, 94:9, 95:11}
firm1 = pd.Series(f1,index=years)
print(firm1)
f2 = {90:14,92:9, 93:13, 94:5}
firm2 = pd.Series(f2,index=years)
firm2
f3 = {93:10, 94:12, 95: 13}
firm3 = pd.Series(f3,index=years)
firm3
df3 = pd.DataFrame(columns=['Firm1','Firm2','Firm3'],index=years)
df3
df3.Firm1 = firm1
df3.Firm2 = firm2
df3.Firm3 = firm3
df3

90     8
91     9
92     7
93     8
94     9
95    11
dtype: int64


Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [72]:
firm2

90    14.0
91     NaN
92     9.0
93    13.0
94     5.0
95     NaN
dtype: float64

In [73]:
df3.dropna()



Firm1  Firm2  Firm3
93      8   13.0   10.0
94      9    5.0   12.0

In [74]:
df3

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In case of DataFrame, <b>if you use dropna, it deletes entire row by default</b>. Another way is to drop only <b>those rows that are all NA</b>. If you want to <b>drop columns, pass axis=1</b>

In [75]:
cleandf3 = df3.dropna(axis=1)          # Drop row if any value in the row is NaN
cleandf3

Firm1
90      8
91      9
92      7
93      8
94      9
95     11

In [76]:
df3

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [77]:
clean2 = df3.dropna(how='all')   # Drop row if all values in the row are NaN
clean2

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [78]:
columndrop = df3.dropna(axis=1)   # Drop column if any value in the column is NaN
columndrop

Firm1
90      8
91      9
92      7
93      8
94      9
95     11

In [79]:
df3

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [80]:
thresholddf = df3.dropna(axis=1,thresh=5)    # Define threshold. In this case row having >= 2 NaN, drop the row
print(thresholddf)
df3


    Firm1
90      8
91      9
92      7
93      8
94      9
95     11


Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [81]:
fillna1 = df3.fillna(0)      # Fill all NaN values with 0
fillna1

Firm1  Firm2  Firm3
90      8   14.0    0.0
91      9    0.0    0.0
92      7    9.0    0.0
93      8   13.0   10.0
94      9    5.0   12.0
95     11    0.0   13.0

In [82]:
fillna2 = df3.fillna({'Firm1':8, 'Firm2': 10, 'Firm3':14})   # We can specify what value should be replaced
fillna2

Firm1  Firm2  Firm3
90      8   14.0   14.0
91      9   10.0   14.0
92      7    9.0   14.0
93      8   13.0   10.0
94      9    5.0   12.0
95     11   10.0   13.0

In [83]:
df3

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [84]:
fillna3 = df3.fillna(method='ffill')    # Forward fill NaNs for 1 level. Check Firm 2 -> 14 & 5
fillna3

Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9   14.0    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    5.0   13.0

In [85]:
fillna4 = df3.fillna(method='bfill')    # Back fill NaNs till 2 levels before. Check how Firm3 behaves
fillna4

Firm1  Firm2  Firm3
90      8   14.0   10.0
91      9    9.0   10.0
92      7    9.0   10.0
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0

In [86]:
#print(df3.mean())
print (df3)
fillna5 = df3.fillna(df3.mean())  # We will substitute empty values with Mean of the Firm in concern
fillna5

    Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0


Firm1  Firm2      Firm3
90      8  14.00  11.666667
91      9  10.25  11.666667
92      7   9.00  11.666667
93      8  13.00  10.000000
94      9   5.00  12.000000
95     11  10.25  13.000000